import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { BackgroundBeamsWithCollision } from "@/components/ui/background-beams-with-collision";
import Navbar from "@/components/Navbar";



export const metadata: Metadata = {
  title: "Developer Club",
  description: "Generated by create next app",
};

const inter = Inter({ subsets: ["latin"] });
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <div className="relative dark w-full">
      <div className="relative dark  w-full flex items-center justify-center"><Navbar/></div>
      {children}
      </div>
      
      </body>
    </html>
  );
}
